// evmone: Fast Ethereum Virtual Machine implementation
// Copyright 2026 The evmone Authors.
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <filesystem>
#include <span>
#include <vector>

namespace evmone::test
{
/// The JSON test files under @p root, sorted, so a run visits them in a stable order.
/// "index.json" is skipped: those are lists of tests generated by other tools, not tests.
[[nodiscard]] std::vector<std::filesystem::path> collect_test_files(
    const std::filesystem::path& root);

/// Drops from @p files everything under one of the @p ignored paths, which are relative to
/// @p root. Whole path components are matched, so ignoring "bc4895" keeps "bc4895-withdrawals".
void ignore_test_files(std::vector<std::filesystem::path>& files, const std::filesystem::path& root,
    std::span<const std::filesystem::path> ignored);
}  // namespace evmone::test
